server:
  port: ${PORT:0}
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  

spring:
  application:
    name: ve-voto-eletronico
  jpa:
    database: MYSQL
    show-sql: true
#    hibernate:
#      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/rf-voto-eletronico?createDatabaseIfNotExist=true&useSSL=false
    username: renanfretta
    password: Ren@nFretta1986
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt_BR