server:
  port: 8761
 
eureka:
  server:
    renewal-percent-threshold: 0.85
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false  

spring:
  application:
    name: ve-eureka-server