server:
  port: 8761
 
eureka:
  instance:
    hostname: localhost
    homePageUrl: https://${eureka.hostname}/
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: true

spring:
  application:
    name: ve-eureka-server