server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

spring:
  application:
    name: ve-api-gateway
  cloud:
    gateway:
      routes:
      - id: veVotoEletronico
        uri: lb://VE-VOTO-ELETRONICO
        predicates:
        - Path=/**
      discovery:
        locator:
          enabled: true