#server:
#  port: ${PORT:0}
 
eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

spring:
  application:
    name: ve-voto-eletronico
  jpa:
    database: MYSQL
    show-sql: true
#    hibernate:
#      ddl-auto: update
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/rf-voto-eletronico?createDatabaseIfNotExist=true&useSSL=false}
    username: ${JDBC_DATABASE_USERNAME:renanfretta}
    password: ${JDBC_DATABASE_PASSWORD:Ren@nFretta1986}
  rabbitmq:
    virtualhost: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt_BR
    
votoeletronico:
  userinfoapiurl: https://user-info.herokuapp.com
  quantidademinutosessaovotacaopadrao: 1